Add exclude_hidden to dict()
roman-right/beanie pull request #178
Opened 2021-12-27 11:52 UTC by yallxe

Previously, when exclude param was provided, hidden fields were not excluded. This commit should fix this issue.

Still, if somebody do not want to exclude hidden fields, he can use `.dict(exclude_hidden=False)`, then, only fields `exclude` will work.

2021-12-29 12:57 UTC, roman-right commented
Thank you for the PR. It looks very neat.

There is a potential conflict here. Pydantic allows using dicts and sets as excludes:
https://pydantic-docs.helpmanual.io/usage/exporting_models/#advanced-include-and-exclude

If exclude parameter is dict, this merge will use only keys of it. 

Please, add tests for this.

2021-12-29 12:57 UTC, roman-right requested changes

2021-12-29 12:57 UTC, roman-right commented on beanie/odm/documents.py
> +            exclude = self._hidden_fields if not exclude else {*self._hidden_fields, *exclude}
This merge doesn't cover case, where exclude parameter is dict

2021-12-29 16:12 UTC, yallxe commented
Well, I've just tried to fix this issue. I think there is a problem with pydantic.

I copied code from https://pydantic-docs.helpmanual.io/usage/exporting_models/#advanced-include-and-exclude to python console (using pydantic 1.8.2) and got an exception:
![image](https://user-images.githubusercontent.com/82591945/147681336-9f857d92-b50f-449c-bf67-4fd098e62f8f.png)

Same issue I have on pydantic 1.7, one that beanie is using.
Python version: 3.10

May I commit my changes that **probably must** allow `exclude` to be dict? Changes include tests also.

2021-12-29 16:27 UTC, roman-right commented
You are right, I see the same problem.
I'll make an issue to the pydantic and a PR, if I'll have time this week. Let's wait till this be fixed to not rework twice.

2022-01-04 20:51 UTC, yallxe commented
Issue fixed in pydantic 1.9.0
Should beanie migrate to latest pydantic or some tests won't pass?

2022-01-05 11:00 UTC, yallxe commented
All tests passed on my hardware, approve me please to run workflows so we can check to check all the versions.

2022-01-05 13:28 UTC, roman-right requested changes

2022-01-05 13:28 UTC, roman-right commented on tests/odm/test_fields.py
> +async def test_param_exclude(document):
It is better to use pytest parametrizing here. Using it you can set input values and expected results. With it you will avoid loops and if-else stuff here.
https://docs.pytest.org/en/6.2.x/parametrize.html

2022-01-05 13:28 UTC, roman-right commented on tests/odm/test_fields.py
> +        print(x)
kill it :)

2022-01-05 13:47 UTC, yallxe commented
I've removed `ExcludeTestCase`. Now it looks better for me.

2022-01-06 11:00 UTC, merged