Redis cache
roman-right/beanie pull request #275
Opened 2022-05-29 03:08 UTC by efirvida

I thought it would be a good idea to have several caching strategies, so I modified a bit the cache API to give ideas of how it could be, for example, to use Redis as a caching system.

```python
import redis
from beanie import Document
from beanie.odm.cache import RedisCache, LRUCache

redis_client = redis.Redis(host='localhost', port=6379, db=0)

class Product(Document):
    name: str
    ...

    class Settings:
        use_cache = True
        cache_system = RedisCache(redis_client)

class User(Document):
    name: str
    ...

    class Settings:
        use_cache = True
        cache_system = LRUCache(
            capacity=32, expiration_time=timedelta(seconds=10)
        )

```

2022-05-30 14:56 UTC, roman-right commented
Oh wow! Great! I'll check everything and merge it tomorrow. Thank you for this feature

2022-05-31 16:43 UTC, roman-right commented
It looks like it breaks some tests

2022-05-31 18:41 UTC, efirvida commented
> It looks like it breaks some tests

Hi!, I'm, not surprised. This was just an idea to work on, that came to me on a project that I want to use Beanie. And also because  I'm learning about Redis as a caching system.

I did not expect such a quick and positive reaction to my proposal. I'm going to work it better to make it ready for merge. Because even the RedisCashe implementation is very poor at this point.

2022-06-01 19:50 UTC, efirvida commented
@roman-right, I have made some fixes and improved de Redis cache system with msgpack as serialization and add ttl.

But there is something strange that my first commit brake (f6614c4ccf4ed8613c70c1d23d174c4af6ef3f79) some test "no cache-related" from my point of view its the same thing but not for the test.

if I change this:

```
    @classmethod
    def init_cache(cls) -> None:
        """
        Init model's cache
        :return: None
        """
        if cls.get_settings().use_cache:
            cls._cache = cls.get_settings().cache_system

```
 for this:

```
    @classmethod
    def init_cache(cls) -> None:
        """
        Init model's cache
        :return: None
        """
        if cls.get_settings().use_cache:
            cls._cache = LRUCache(capacity=5, expiration_time=datetime.timedelta(seconds=10))

```

Which I think is the same thing all test runs, but not if I init the cache from the Document's `cache_system` settings

2022-06-02 21:17 UTC, efirvida commented
> 0c9d28e

Fixed here [0c9d28e](https://github.com/roman-right/beanie/pull/275/commits/0c9d28e00a54731df0774e1ba3f611b03356485f)

2022-06-02 21:29 UTC, efirvida commented
Now it's working, here is an example code

```python

import redis
import msgpack
import json
import pickle
from typing import Optional
from datetime import timedelta

from beanie.odm.cache import LRUCache,RedisCache

redis_client = redis.Redis(host='localhost', port=6379, db=0)

class ProductNoCache(Document):
    name: str
    description: Optional[str] = None
    price: Indexed( float ) 
    class Settings:
        use_cache = False


class ProductRedisPickle(Product):
    class Settings:
        use_cache = True
        cache_system = RedisCache(redis_client, serializer=pickle) # pickle is default serializer


class ProductRedisJSON(Product):
    class Settings:
        use_cache = True
        cache_system = RedisCache(redis_client, serializer=json, ttl=timedelta(seconds=10)) # use ttl for expiration
        
       
class ProductRedisMsgPack(Product):
    class Settings:
        use_cache = True
        cache_system = RedisCache(redis_client, serializer=msgpack, ttl=10) # ttl can be int -> 10 seconds


class ProductLRUCache(Product):
    class Settings:
        use_cache = True
        cache_system = LRUCache(capacity=5, expiration_time=timedelta(seconds=10))```

2022-06-17 18:35 UTC, roman-right commented
Wow! You worked a lot here. Thank you!
I'll check everything this weekend.

2022-06-21 13:23 UTC, roman-right requested changes

2022-06-21 13:23 UTC, roman-right commented on beanie/odm/cache.py
> +            if "_id" in value:
I would use a type-based custom serializer for msgpack or json

2022-06-21 13:23 UTC, roman-right commented on pyproject.toml
> +redis = "^4.3.1"
it would be great to have these guys as extra dependencies: https://python-poetry.org/docs/pyproject#extras

2022-06-21 13:23 UTC, roman-right commented on tests/odm/documents/test_bulk_write.py
> +    DocumentTestModel.invalidate_cache()
as this is not a part of the test, it is better to move it as a fixture to the modular conftest file and run it in `autouse=True` mode

2022-06-21 13:23 UTC, roman-right commented on beanie/odm/cache.py
> +            return None
I didn't get the logic here. I think, users should know, that the cache is broken. May be I don't see something

2022-07-27 08:03 UTC, Luc1412 requested changes

2022-07-27 08:03 UTC, Luc1412 commented on beanie/odm/cache.py
> +    def invalidate(self) -> None:
All Redis action should be async as beanie is async too. This could introduce blocking behaviour.

2023-02-16 02:38 UTC, closed without merging